# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

healthCheckTimeout: 500
logLevel: info
logToStdout: "proxy"
sendLoadingState: true

globalTTL: 600

startPort: 5800

macros:
  "llama-server": "./llama-server --port ${PORT} -ngl 99"

# apiKeys:
#   - "sk-change-me"

models:
  "unsloth/gpt-oss-20b-GGUF:UD-Q4_K_XL":
    macros:
      "ctx_size": 16384
      "temperature": 1.0
      "top_p": 1.0
      "top_k": 40
    cmd: |
      ${llama-server}
      -hf unsloth/gpt-oss-20b-GGUF:UD-Q4_K_XL
      --ctx-size ${ctx_size}
      --jinja
      -ub 2048 
      -b 2048
      --temp ${temperature}
      --top-p ${top_p}
      --top-k ${top_k}
      --chat-template-kwargs '{"reasoning_effort": "high"}'

  "unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL":
    macros:
      "ctx_size": 16384
      "temperature": 1.0
      "top_p": 0.95
      "top_k": 64
    cmd: |
      ${llama-server}
      -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
      --ctx-size ${ctx_size}
      --temp ${temperature}
      --top-p ${top_p}
      --top-k ${top_k}
      --chat-template-kwargs '{"enable_thinking":true}'
