[*]
ctx-size = 0
jinja = true
b = 2048
ub = 2048
reasoning = auto
flash-attn = on
cache-type-k = q4_0
cache-type-v = q4_0

[GPT-OSS 20B (Low)]
alias = gpt-oss-20b-low
hf = unsloth/gpt-oss-20b-GGUF:UD-Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
reasoning = on
chat-template-kwargs = {"reasoning_effort": "low"}

[GPT-OSS 20B (Medium)]
alias = gpt-oss-20b-medium
hf = unsloth/gpt-oss-20b-GGUF:UD-Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
reasoning = on
chat-template-kwargs = {"reasoning_effort": "medium"}
; load-on-startup = true

[GPT-OSS 20B (High)]
alias = gpt-oss-20b-high
hf = unsloth/gpt-oss-20b-GGUF:UD-Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
reasoning = on
chat-template-kwargs = {"reasoning_effort": "high"}

[Gemma 4 E4B]
alias = gemma-4-e4b
hf = unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL
temp = 1.0
top-p = 0.95
; top-k = 64
top-k = 20 ; Temporarily set to 20 to improve performance, should be increased after LlamaCpp patches
reasoning = on
image-min-tokens = 300
image-max-tokens = 512
; Temp fixes for Gemma 4, shouldn't be needed after LlamaCpp patches
no-mmap = true
ctx-size = 65536
cache-ram = 0
ctx-checkpoints = 1
parallel = 1

[Gemma 4 26B A4B]
alias = gemma-4-26b-a4b
hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
temp = 1.0
top-p = 0.95
; top-k = 64 ; Temporarily set to 20 to improve performance, should be increased after LlamaCpp patches
top-k = 20
reasoning = on
image-min-tokens = 300
image-max-tokens = 512
; Temp fixes for Gemma 4, shouldn't be needed after LlamaCpp patches
no-mmap = true
ctx-size = 65536
cache-ram = 0
ctx-checkpoints = 1
parallel = 1
